### PR TITLE
Add specific variables for PWM control, rather than sharing SpeedData…

### PR DESCRIPTION
**Pull request by btsimonh**
… - must be matched in main.c!!!

### CODE REVIEW

**Comment by btsimonh** [comment]
another push coming; hold this a moment.

**Comment by btsimonh** [comment]
ok, both done.  flash write (or read) does not work :(.

**Comment by p-h-a-i-l** [comment]
when was the last time it was working? Can you manipulate flash through ASCII protocol?

**Review by p-h-a-i-l — COMMENTED** [review]
Looks good, I also aligned my lightweight command to be less confusing. Not tested, and right now I can not help with your Flash. I might have damaged something in my #ifdef spree..

**Pull request merged**
